; v1.0 (Aug 16 2026)
; by Hypercycle
; 1 means Yes, 0 means No
; Make sure to disable the "Widescreen" option in the game settings to avoid any issues.



[Display]
; Enable the Display settings down below. 
EnableDisplayTweaks = 1

; Current screen resolution, same as the Screen Resolution option in-game.
; Note: the chosen resolution must also be available in your operating system's display properties.
; Set both to 0 to automatically get the resolution from your current display video mode.
ScreenWidth = 0
ScreenHeight = 0

; The game will display a set of video mode resolutions in the menu settings, depending on the chosen Aspect Ratio.
; Note: the chosen aspect ratio and resolutions must also be available in the display properties of your operating system.
; The game's default is 4 - 3.
; Set both to 0 to automatically select the aspect ratio from your current display video mode, or your current config screen resolution.
VideoModeAspectWidth = 0
VideoModeAspectHeight = 0

; Enable proper Field of View scaling for custom aspect ratios.
EnableFOVScaling = 1

; Enable proper horizontal scaling of the User Interface for custom aspect ratios.
; Note: menu FOV for 3D elements will be incorrect without this option.
EnableUIScaling = 1

; Load the GUI files under different names to avoid overwriting the original files.
ReplaceGUIPaths = 1



[Settings]
; Toggle this .asi script.
EnableASI = 1

; Skip all intro movies. Set to 0 if you want the EA logo and trailer movie to play at the start of the game.
SkipMovies = 1

; Bigger screen size for the movies. Please note that it won't be an exact match for the size of an actual screen, due to the way the game scales movie playback.
IncreaseMovieViewScale = 1

; Do not trigger the safety check after a game crash during a change of window mode.
; Originally, after a game crash, a new file called "togglewindowtest.txt" would appear in the SaveData folder. If this file exists, the Alt+Enter window mode toggle will not work.
DisableFullscreenSafetyCheck = 1

; Set the GPU memory size value to be loaded by the game. The integer value for the available GPU memory could overflow by default on modern GPUs. The value is given in megabytes.
GPUMemorySize = 128

; By default, the game forces the window into fullscreen mode when it starts up, regardless of your in-game settings.
; This fix enables the game to render the initial black screen in a window when it runs in Windowed mode.
DisableForcedInitFullscreen = 1

; Always start the game in Windowed mode. Do not enable this option unless it is necessary.
ForceWindowedModeOnInit = 0

; Instead of looking in the Registry, check the current relative game folder path to allow the launch of different game builds (Debug + Sunset), or to enable the game folder to be moved for better portability.
; Warning: the original mco.exe login with the Offline Debug launcher still requires registry path values.
NonRegGameExecutablePath = 1

; Toggle the test Console window.
EnableTestConsole = 0