# Fix for glitched UI rendering
d3d8.managedBufferPlacement = False

# Huge performance fix
d3d9.apitraceMode = True

# Overrides the application's MSAA level on the swapchain
# Supported values: -1 (application) and 0 to 16 (user override)
d3d9.forceSwapchainMSAA = -1